version: '3.9'

services:
  web:
    build: ../src
    # command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "
        sleep 5 &&
        python manage.py migrate &&
        gunicorn api.wsgi:application --bind 0.0.0.0:8000 --timeout 120
      "
    # command: >
    #   sh -c "
    #     sleep 5 &&
    #     python manage.py migrate &&
    #     python manage.py runserver 0.0.0.0:8000
    #   "
    volumes:
      - ../src:/app
    ports:
      - "8000:8000"
    env_file:
      - ../src/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recordsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  worker:
    build: ../src
    command: celery -A api worker -l info
    volumes:
      - ../src:/app
    depends_on:
      - redis
      - web
      - postgres

volumes:
  pgdata: